kind: Service
apiVersion: v1
metadata:
  name: mongodb-svc
  namespace: sim
  labels:
    app: mongodb
spec:
  clusterIP: None
  selector:
    app: mongodb
  ports:
    - protocol: TCP
      targetPort: 27017
      port: 27017
  
