kind: PersistentVolume
apiVersion: v1
metadata:
  name: sim-pv
  namespace: sim
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  hostPath:
    path: '/tmp/sim-data'
