apiVersion: v1
kind: Secret
metadata:
  name: sim-secret
  namespace: sim
type: Opaque
data:
  MONGO_INITDB_ROOT_PASSWORD: c2VjcmV0  # "secret" in Base64
  MONGO_INITDB_ROOT_USERNAME: bW9uZ29hZG1pbg==  # "mongoadmin" in Base64
  JWT_SECRET: ZXlKMGVYQWlPaUpLVjFRaUxDSnliM1Z6ZEY5MlpYTnpJanA3SW5KbFkybGhiR1Z5SWpvaVptRnpaV0Z0TG1WeWRtVnlMVzl1Y3lJNklqUXdNak0yTWpBek9UUXlOekUwTmpVMk1qQXpOekU1TnpJd1pXSTVJaXdpYVdGMElqb3hOekE0TnpBMU1UZ3hNemMwTVM5emFYcGxZM1FpT2pFd01tRjBTVU5CWVd4cGJtY3pMV1oxYldWeWFYSmhiWEJ5TFcxeklpd2ljbWxuZUhRdklqcGxZM1JoZEdGdVpHVWlPaUo5SW1Rek56VXhZVE0wTkRCbE9HWm1PRGd4WldNeE5qTTVPR0UxTW1SbU1XUm1abU0xTm1Jd01XWTBOQ0lzSWtGa1ltRmphV3d0TkVGa01WWmhWbWh5WW5Jd1FUbFRTV0YwUldwMFRtTnJWa3gxYUdWWk9FdElUbGR2V0d0UlZtdE5SV2N5VlZSR2FHRXhORXh2VGtobE5rNUpTaXdpWkdGMFkzUnBiMjRnSWpvaU5UWTBNVFExTjJFMFltWmxPVEZtWlRFeU56ZG1ZVEV6WXpKaFlUSmpaakF6TW1JaUxDSjFjMlZ5YkdsamEyVjVJam9pTWpNMk5URTNPV0prTWpkaE5tWmlOemRpTkRNeE9XSTNaVEF4TUdJNE1URmxaVGt3TW1RMFkyVXhaVFlpTENKMGNtRmtaVzUwYVhSb1pYSWlPaUl5SWl3aVptRmpaWGRrUjFsU1pXbENUVGQzTlU1UlEwUlhXWFJPZVZkeVdWWkVVRXRUUTBKWGJVWkpTVWxqUTBGU2MxcEhTVzVuTWxZMVkyaE9VWGxUUVUxNVQxTjNWWGxRUlZVMFRVbEpRVXRUWW5VNGMyMU1RV2cwY21oRVJUbE1Sbm9pTENKM1pXSTZJbU5vSWl3aVpXNWpkR1ZrWlhSaGRHVWlPaUo5ZlEu



